# -*- coding: utf-8 -*-
"""DesafiodaJornadaPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrSIDwQtKy6luqik5TA02tR0p1JAu9wv
"""

print ('Matheus Ricardo')

nome = input("Insira seu nome: ")

nota1 = float(input("Sua primeira nota: "))
nota2 = float(input("Sua segunda nota: "))

print("Olá", nome, "sua notas foram:")
print(nota1, "e", nota2)

soma = nota1 + nota2
media = soma / 2

print("Sua média é", media)